name: lint-test

on: [push, pull_request]

env:
  GO_VERSION: "^1.17"
  GOLANGCI_LINT_VERSION: "v1.43.0"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$(go env GOPATH)"/bin ${{ env.GOLANGCI_LINT_VERSION }}
    - uses: actions/checkout@v2
    - name: Lint code
      run: make lint

  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test
